export const OAUTH2_SERVER_INSTANCE = Symbol('OAUTH2_SERVER_INSTANCE');
export const OAUTH2_SERVER_OPTIONS = Symbol('OAUTH2_SERVER_OPTIONS');
export const OAUTH2_SERVER_OPTIONS_METADATA = Symbol(
  'OAUTH2_SERVER_OPTIONS_METADATA',
);
