export const OAUTH2_SERVER = Symbol('OAUTH2_SERVER');
export const OAUTH2_SERVER_OPTIONS = Symbol('OAUTH2_SERVER_OPTIONS');
export const OAUTH2_SERVER_MODEL = Symbol('OAUTH2_SERVER_MODEL');
export const OAUTH2_SERVER_MODEL_METADATA = Symbol('OAUTH2_SERVER_MODEL_METADATA');
export const OAUTH2_SERVER_HANDLER_OPTIONS_METADATA = Symbol('OAUTH2_SERVER_HANDLER_OPTIONS_METADATA');
